production:
  base:
    registration: false
  mailer:
    default_from: noreply@reckoning.io
    host:
    port: 587
    user:
    password:
  demo: true
  app:
    url: "http://reckoning.dev"
    domain: "reckoning.dev"
    gdrive_collection: "Reckoning.io"
    py_env:
development:
  base:
    registration: false
  mailer:
    default_from: noreply@reckoning.io
    host:
    port: 587
    user:
    password:
  demo: true
  app:
    url: "http://reckoning.dev"
    domain: "reckoning.dev"
    gdrive_collection: "Reckoning.io"
    py_env:
test:
  base:
    registration: true
  mailer:
    default_from: reckoning@example.com
    host:
    port:
    user:
    password:
  app:
    url: "http://reckoning.dev"
    domain: "reckoning.dev"
    gdrive_collection: "Reckoning.io"
    py_env:
